version: $env:SERVICE_VERSION:0.0.1
weChatConfiguration:
  weChatAppId: $env:WECHAT_APP_ID:
  weChatAppSecret: $env:WECHAT_APP_SECRET:
  weChatToken: $env:WECHAT_APP_TOKEN:

publicAddress: $env:PUBLIC_PUBLIC:
publicPath: $env:LOCAL_PUBLIC:

# Logging settings.
logging:
    # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
    level: INFO

    # Logger-specific levels.
    loggers:
      # Sets the level for 'com.example.app' to DEBUG.
      io.dropwizard: INFO
      org.hibernate: INFO
      org.madtribe : DEBUG

    appenders:
      - type: console