example-wechat-app:
  image: java:8
  ports:
    - 8080:8080
    - 8081:8081
  volumes:
    - $JAR_PATH/$JAR_NAME:/opt/$SERVICE_NAME/$JAR_NAME
    - $CONFIG_PATH:/opt/$SERVICE_NAME/config
    - ../public:/opt/$SERVICE_NAME/public
  environment:
    SAMPLE_WECHAT_APP_ID: $SAMPLE_WECHAT_APP_ID
    SAMPLE_WECHAT_APP_SECRET: $SAMPLE_WECHAT_APP_SECRET
    SAMPLE_WECHAT_APP_TOKEN: $SAMPLE_WECHAT_APP_TOKEN
  working_dir: /opt/$SERVICE_NAME
  command: >
    java -jar $JAR_NAME server /opt/$SERVICE_NAME/config/$CONFIG_FILE